/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrowdfundingRouteImport } from './routes/crowdfunding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsDetailsRouteImport } from './routes/payments.details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdfundingRoute = CrowdfundingRouteImport.update({
  id: '/crowdfunding',
  path: '/crowdfunding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsDetailsRoute = PaymentsDetailsRouteImport.update({
  id: '/payments/details',
  path: '/payments/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crowdfunding': typeof CrowdfundingRoute
  '/login': typeof LoginRoute
  '/payments/details': typeof PaymentsDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crowdfunding': typeof CrowdfundingRoute
  '/login': typeof LoginRoute
  '/payments/details': typeof PaymentsDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crowdfunding': typeof CrowdfundingRoute
  '/login': typeof LoginRoute
  '/payments/details': typeof PaymentsDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crowdfunding' | '/login' | '/payments/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crowdfunding' | '/login' | '/payments/details'
  id: '__root__' | '/' | '/crowdfunding' | '/login' | '/payments/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrowdfundingRoute: typeof CrowdfundingRoute
  LoginRoute: typeof LoginRoute
  PaymentsDetailsRoute: typeof PaymentsDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowdfunding': {
      id: '/crowdfunding'
      path: '/crowdfunding'
      fullPath: '/crowdfunding'
      preLoaderRoute: typeof CrowdfundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/details': {
      id: '/payments/details'
      path: '/payments/details'
      fullPath: '/payments/details'
      preLoaderRoute: typeof PaymentsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrowdfundingRoute: CrowdfundingRoute,
  LoginRoute: LoginRoute,
  PaymentsDetailsRoute: PaymentsDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
