/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrowdfundingRouteImport } from './routes/crowdfunding'
import { Route as PaymentsPaymentIdRouteImport } from './routes/payments.$paymentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdfundingRoute = CrowdfundingRouteImport.update({
  id: '/crowdfunding',
  path: '/crowdfunding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPaymentIdRoute = PaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crowdfunding': typeof CrowdfundingRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crowdfunding': typeof CrowdfundingRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crowdfunding': typeof CrowdfundingRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crowdfunding' | '/payments/$paymentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crowdfunding' | '/payments/$paymentId'
  id: '__root__' | '/' | '/crowdfunding' | '/payments/$paymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrowdfundingRoute: typeof CrowdfundingRoute
  PaymentsPaymentIdRoute: typeof PaymentsPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowdfunding': {
      id: '/crowdfunding'
      path: '/crowdfunding'
      fullPath: '/crowdfunding'
      preLoaderRoute: typeof CrowdfundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$paymentId': {
      id: '/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof PaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrowdfundingRoute: CrowdfundingRoute,
  PaymentsPaymentIdRoute: PaymentsPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
