spring.application.name=payment-processing-system
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:payment_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:n3u3da!}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8082
spring.sql.init.mode=always


