package com.paymentprocessing.payment_processing_system.enums;

public enum ErrorCode {

    VALIDATION_FAILED,
    INVALID_AMOUNT,
    INVALID_ACCOUNT,
    INVALID_CURRENCY,
    INSUFFICIENT_FUNDS,
    DUPLICATE_PAYMENT,
    INVALID_STATUS_TRANSITION,
    PAYMENT_NOT_FOUND,
    PROCESSING_ERROR,
    NETWORK_ERROR,
    REFUND_ERROR,
    CRYPTO_ERROR,
    CAMPAIGN_ERROR,
    CONTRIBUTION_ERROR,
    EXCHANGE_RATE_ERROR,
    NOTIFICATION_ERROR,
    AUDIT_ERROR

}